theme: jekyll-theme-hacker
title: HackAndPwn
tagline: Security & Vulnerability Researcher / Professional Penetration Tester
url: https://hackandpwn.com
paginate: 1
  per_page: 10
baseurl: ""
permalink: :title/